<?php
/**
 * @file
 * .module file for 'the_curtain' module
 */

/**
 * Implements hook_menu() 
 */
function the_curtain_menu() {
  $menu['admin/config/development/the_curtain'] = array(
    'title' => 'The Curtain',
    'description' => 'Nevermind the man behind the curtain.',
    'page callback' => 'the_curtain_admin_page',
    'access arguments' => array('access administration pages'),
    'file' => 'the_curtain.admin.inc',
  );
  $menu['admin/config/development/the_curtain/unveil'] = array(
    'title' => 'Unveilings',
    'description' => 'Show behind-the-scenes data from Drupal.',
    'page callback' => 'the_curtain_admin_unveilings',
    'access arguments' => array('the curtain unveil'),
    'file' => 'the_curtain.admin.inc',
  );
  return $menu;
}

/**
 * Implements hook_permission
 */
function the_curtain_permission() {
  return array(
    'the curtain unveil' => array(
      'title'=> t('Unveil the inner workings of Drupal'),
      'description' => t('Show things such as SQL strings, form data, etc. on pages.'),
    ),
  );
}

/**
 * Implements hook_query_alter()
 * Displays the all available queries to the UI
 */
function the_curtain_query_alter(SelectQueryInterface $query) {
  if ( variable_get('the_curtain_show_sql') ) {
    module_load_include('inc', 'the_curtain', 'the_curtain.utils');
    drupal_set_message(_the_curtain_query_to_sql($query));
  }
}

function the_curtain_form_alter($form, &$form_state) {
  if ( variable_get('the_curtain_show_forms') ) {
    kpr($form);
  }
  if ( variable_get('the_curtain_show_form_states') ) {
    kpr($form_state);
  }
}
